### ISSUE TITLE
Using accessible color in reports

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/PACE-HRH#230]
@CWiswell-IDM commented on the validation report
https://github.com/InstituteforDiseaseModeling/PACE-HRH/blob/main/validation_report.Rmd#L14-L17
https://github.com/InstituteforDiseaseModeling/PACE-HRH/blob/main/ValidateInput_plot.R#L35
may not be color-blind friendly
maybe using these palettes? http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette
@ptrdo any suggestions?

**Comment by ptrdo** [comment]
IMHO, color-blindness ought not be the prescribing factors unless it's known that a significant number of the intended audience is known to be color blind (~8% of men, but to varying degree, many not severe). More important is that the chosen colors are distinct from one another and express the desired alarm. 

Here is a browser plug-in (for Chrome) that will demonstrate various forms of color blindness. Though keep in mind that some of these are very rare and virtually uncorrectable with any feasible palette. 

https://chrome.google.com/webstore/detail/colorblindly/floniaahmccleoclneebhhmnjgdfijgg?hl=en

If someone wants to grab a screen capture of the result of this project, I would be happy to assess it (from my opinion).

**Comment by MeWu-IDM** [comment]
@ptrdo thanks for the feedback, for the validation report, the color doesn't seem to get adjusted from the plugin (attached one file here if you want to check) 
[validation_report.zip](https://github.com/InstituteforDiseaseModeling/PACE-HRH/files/10512590/validation_report.zip)

**Comment by ptrdo** [comment]
@CWiswell-IDM @MeWu-IDM The plug-in won't work with an image, so I used Photoshop to convert the rendered chart for the most common form of color-blindness (red-green, deuteranomaly). The most offensive color is the “limegreen” (#32cd32) which is seen by a color-blind person as very close to the “goldenrod.” However, if **instead of “limegreen” we use “downy”** (#69d0be), then that color is seen as light grey, and distinguishes itself nicely from the others. 

![validation-deuteranomaly-original](https://user-images.githubusercontent.com/110694/214943415-2b2d23af-6b92-4d71-aa31-dd1bc68424a2.png)

![validation-deuteranomaly-adjusted](https://user-images.githubusercontent.com/110694/214943469-bd55bf19-0380-4359-8a55-1157564323df.png)

**Comment by ptrdo** [comment]
IMHO, downy is a little easier on normal eyes too (as opposed to limegreen).

**Comment by MeWu-IDM** [comment]
@ptrdo thanks! I like this!  since I am doing some changes in the report I updated the color https://github.com/InstituteforDiseaseModeling/PACE-HRH/pull/228/commits/bce173e48d2998a57eddea78038415309b10ce2c
